---
- name: Update package cache
  dnf:
    update_cache: yes
  become: yes

- name: Install Python
  dnf:
    name: python3
    state: present
  become: yes

- name: Install pip
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Python Library
  pip:
    name:
      - docker
      - docker-compose
  become: yes

- name: Run Container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8282:82"
    state: started
  become: yes
